### ISSUE TITLE
Create Data Sync

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#157]

**Comment by SferaDev** [comment]
For on-demand data synchronization we can easily have the following:

- Two main filters enforced to ObjectsTable to load: OrganisationUnit/OrganisationUnitGroup and Period
- Table would be filled by all the values detected on current instance allowing to select only the data user wants to migrate on-demand.
- Extra filter for DE and/or CO from the list

The API does allow to only provide 2 of the 4 dimensions in the query and we can easily preview what data the user wants to migrate instead of blindly migrating all data on-demand (Sync Rules is different in the means that data to be migrated will vary over time).
