### ISSUE TITLE
Create Data Sync Rule

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#158]
- [x] Skeleton (See #166)
- [x] Step 1: General Info
- [x] Step 2: Selection of DEs/Ind
- [x] Step 3: Selection of Org Units
- [x] Step 4: Selection of Period
- [x] Step 5: Selection of Category Option
- [x] Step 6: Selection of Instances
- [x] Step7: Scheduling
- [x] Step 8: Summary

**Comment by SferaDev** [comment]
As far as I recall the API has some advantages that we can use, adding here some points for discussion:

- Endpoints allows both OrgUnit or OrgUnitGroup selection
- Usage might require an ALL rule for period and/or orgUnit
- I believe CO page will not be an ObjectsTable since we do not support disaggregation and it is done per dataElement. I would consider something like the greyed fields page on mantainance for that step. 
- Would it make sense to allow filtering on DE page by dataset?

Even though not related to the sync rule specifically:
- Would it be useful to add preview contextual action that compares origin with destination and previews the data/metadata to be imported?
