### ISSUE TITLE
Pull Request Metadata

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/metadata-synchronization#534]
### Original tasks

- [x] Set responsible user or user group 
   - [x] Add contextual action in the manual metadata sync or in a new section to add responsible
   - [x] Contextual action opens a dialog to select user and/or user group from the instance
   - [x] Save responsible linked to a piece of metadata (only Program and dataset)
- [x] On sync, check if there is a metadata or data responsible. If so create a Pull Request, otherwise it should work as now.
   - [x] Create Pull Request on remote instance. 
   - [x] Show form in a dialog with fields: description, author, date, set of metadata or data, other CC user or user group notifier
   - [x] Save Pull Request in data store both in origin and destination. Save JSON in remote for now (you are not allowed to get it).
   - [x] Send internal messaging/email to CC user or user group notifier
- [x] Notifications
   - [x] New section in landing page
   - [x] Show current notifications with the following actions:
      - [x] List notifications in a table with the following columns: read/unread, data/metadata, owner, timestamp, description, status (pending, approved, rejected), sent/received
      - [x] Filters: by status (dropdown), by read/unread, search box
      - [x] On init, check status of sent pull request asking to the remote.
         - [x] If approved, trigger sync
         - [x] If not, update pull request status
      - [x] Actions in remote:
         - [x] Show details. Summary listing the package
         - [x] Approve
            - [x] Update pull request status in data store
            - [x] Save results on history in local
         - [x] Reject
            - [x] Update pull request status in data store
         - [x] Delete (only available for the local)

### Feedback

- [x] Check same user permissions on different instances
- [x] Add pull then pull request dialog if same user is responsible
- [x] Check contextual actions and permissions
- [x] Check role CONFIGURATOR for responsibles add/remove and list in landing page
- [x] Send emails when importing pull request
- [x] Remove "delete" action
- [x] Add cancel in local
- [x] Ensure payload is cleared after successful import
- [x] After updating responsibles, update notifications PENDING (and create new prop on dataStore (responsibles)

**Comment by SferaDev** [comment]
Discussions:

#### Send emails when approving/rejecting

Since remote instance (who receives the pull request notification) does not necessarily know credentials of origin instance, we're unable to send those emails on-demand

#### After updating responsibles, update notifications PENDING (and create new prop on dataStore (responsibles))

After a second thought, I'm not 100% sure about this. Proposal:

- Approve/Reject action always looks up for current responsibles (disregarding who the notification was sent to)
- Notifications receivers are updated after updating responsibles (ie. adding a new responsible makes him to receive pending notifications)
- We do not need a new prop on the dataStore with duplicated info

#### What happens if an instance is not online and/or deleted?

We rely a lot on stored instances for remote connection, what should be the desired behavior for both scenarios?

Regarding the instance is down (not online) scenario, right now we perform the updates locally and show a warning "Could not update remote instance, notification not found". However both instances won't have the notifications in sync.

And regarding the deleted instance scenario, right now we perform the updates locally and show an error "Instance not found". However remote instance will not receive updates never again.
