### ISSUE TITLE
Use transformations in package generation

### ISSUE THREAD

**Issue by tokland** [EyeSeeTea/metadata-synchronization#588]

**Comment by SferaDev** [comment]
The use case ``CreatePackageUseCase`` receives the payload. Instead we should do the same @tokland did in another use case and forward the ``compositionRoot`` to programmatically create the payload for each version.

Also ``apiVersion`` is always read from ``this.instance`` which is not useful when building the ``package``, we should refactor the ``metadataRepository`` to use a provided ``apiVersion`` instead of always relying on the instance.
