### ISSUE TITLE
Review table selection

### ISSUE THREAD

**Issue by SferaDev** [EyeSeeTea/metadata-synchronization#594]
![image.png](https://app.gitkraken.com/api/glo/boards/5da04a8d796a7c000f8784e0/attachments/5f3e85eaab0eea0011ae1c46)

**Comment by tokland** [comment]
Fixed in d2-ui-components:

https://github.com/EyeSeeTea/d2-ui-components/pull/175

With that change, I've been unable to reproduce any problems on the selection/unselection of the table. We'll reopen if we find a case. 

Since there is no change on the app, I recommend a manual update to test the d2-ui-components PR: `yarn add d2-ui-components@2.0.1-beta.4`
